// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config();
dotenv.config({ path: ".env.local" });

/** Percent-encode password in postgres URL so reserved chars like [ ] work (avoids P1001). */
function withEncodedUserinfo(rawUrl: string | undefined): string | undefined {
  if (!rawUrl || !rawUrl.startsWith("postgresql://")) return rawUrl;
  const match = rawUrl.match(/^postgresql:\/\/([^@]+)@([^/]+)(\/.*)?$/);
  if (!match) return rawUrl;
  const [, userinfo, hostPort, path = ""] = match;
  const colonIdx = userinfo.indexOf(":");
  const user = colonIdx === -1 ? userinfo : userinfo.slice(0, colonIdx);
  const password = colonIdx === -1 ? "" : userinfo.slice(colonIdx + 1);
  const encoded = password ? `${user}:${encodeURIComponent(password)}` : user;
  return `postgresql://${encoded}@${hostPort}${path}`;
}

const datasourceUrl = withEncodedUserinfo(process.env["DIRECT_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
